In [13]:
from curses import noecho
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import heapq
import time
import sys
import os
import math
import random
import graphlib
from PIL import Image
import os, sys
import Utilities.utils as utils
import heapq

neighbor_map = [(-1,-1),(0,-1),(1,-1),(-1,0),(1,0),(-1,1),(0,1),(1,1)]

def load_occupancy_map():
	# Read image from disk using PIL
	occupancy_map_img = Image.open('occupancy_map.png')
	occupancy_grid = (np.asarray(occupancy_map_img) > 0).astype(int)
	return occupancy_grid

def Neighbours(graph, v):
    neighbors = []
    for x,y in neighbor_map:
        search_point = (v[0]+x,v[1]+y)
        if graph[search_point] == 1:
            neighbors.append(search_point)
    return neighbors


def distance(v1, v2):
    return math.dist(v1, v2)


In [14]:

from collections import defaultdict


class AStar:
    def __init__(self, graph, start, goal):
        self.graph = graph
        self.vertices = [(i,j) for i in range(self.graph.shape[0]) for j in range(self.graph.shape[1])]
        #print("vertices", self.vertices)
        self.start = start
        self.goal = goal
        print("start = ", self.start)
        print("goal = ", self.goal)
        self.path = []
        self.visited = []
        self.cost = 0
        self.Q = [(distance(start, goal),start)]
        heapq.heapify(self.Q)
        self.Qhelper = {start: distance(start, goal)}
        self.pred = {}
        self.costTo = defaultdict(lambda: float("inf"))
        self.estTotalCost = defaultdict(lambda: float("inf"))
        for v in self.vertices:
            self.costTo[v] = 9999999999999999
            self.estTotalCost[v] = 9999999999999999
        # self.costTo = {v: 9999999999999999 for v in self.vertices}
        # self.estTotalCost = {v: 9999999999999999 for v in self.vertices}
        self.costTo[start] = 0
        self.estTotalCost[start] = distance(start, goal)

    def RecoverPath(self, start, goal, pred):
        #self.path, self.visited, self.cost, self.nodes, self.edges = self.a_star(self.graph, self.start, self.goal)
        current = goal
        #print("pred = ", pred)
        while current in pred:
            #print("current = ", current)
            retracedPath = []
            prevPath = pred[current]
            retracedPath.append(prevPath)
            current = prevPath
            if current == start:
                break
        # if len(self.pred) == 0:
        #     self.path = None
        # elif len(self.pred) == 1:
        #     self.path = [pred[goal], start]
        # else:
        #     if pred[goal] == start:
        #         self.path.append(start)
        #         return self.path
        #     self.path.append(pred[goal])
        #     self.RecoverPath(start, pred[goal], pred)
        # end = time.time()
        #return array with all vertices from start to goal
        return retracedPath

    def a_star(self):
        while self.Q != []:
            v = heapq.heappop(self.Q)[1]
            del self.Qhelper[v]
            if v == self.goal:
                print("goal found")
                return self.RecoverPath(self.start, self.goal, self.pred)
            #print("neighbors of ", v, " = ", Neighbours(self.graph, v))
            for n in Neighbours(self.graph,v):
                #print("n = ", n)
                pvi = self.costTo[v] + distance(v, n)
                if pvi < self.costTo[n]:
                    #The path to i through v is better than the previously-known best path to i,
                    # so record it as the new best path to i.
                    self.pred[n] = v
                    self.costTo[n] = pvi
                    self.estTotalCost[n] = pvi + distance(n, self.goal)
                    if n in self.Qhelper:
                        tmpVal = self.Qhelper[n]
                        self.Q.remove((tmpVal, n ))
                        heapq.heappush(self.Q, (self.estTotalCost[n], n))
                        self.Qhelper[n] = self.estTotalCost[n]
                    else:
                        heapq.heappush(self.Q, (self.estTotalCost[n], n))
                        self.Qhelper[n] = self.estTotalCost[n]



        return []

In [15]:
if __name__ == "__main__":
    occupancyGrid = utils.convertToBinary()
    print(load_occupancy_map())
    astar = AStar(load_occupancy_map(), (635,140),(350,400))
    #neighbors = Neighbours(occupancyGrid, (np.random.randint(2, len(occupancyGrid[0])-2), np.random.randint(2, len(occupancyGrid)-2)))
    #dis = distance((np.random.randint(2, len(occupancyGrid[0])-2), np.random.randint(2, len(occupancyGrid)-2)), (np.random.randint(2, len(occupancyGrid[0])-2), np.random.randint(2, len(occupancyGrid)-2)))
    print(astar.a_star())
    # print(neighbors)
    # print(dis)

Current Directory:  /Users/anushsriramramesh/Library/CloudStorage/OneDrive-NortheasternUniversity/MR/MR-HW3/src
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
start =  (635, 140)
goal =  (350, 400)
goal found
[(635, 140)]
